sudo: false
language: python
python:
- 2.7
os:
- linux
install:
- pip install .
script: cwl-airflow-runner --help
branches:
  only:
  - master
deploy:
  provider: pypi
  user: misha.kotliar@gmail.com
  password:
    secure: "YEszs88pg3HWHWu4dyXIM9V+ze3qOMFIiWTQ7rAu5NtTwOxR6IAS1I7uVWyy5jiQ+GC7eP7ijxFLT9x54Dj0VDR6Atwtxrf8k+zowWrP0Jd5rEEwjDqmw5WOLmYGNP2JMguiYxJZ2MbWncPYwKjy/6SxgZqOUkeZEMHQPoHecViNv59kh56q1tVmlJrQPt9CL2bMln71uy0w7mvilFYclzKfpuU41KWsqwpe4XXzRdFj4IaVCN+w28FydUg0sDoHzo7UriRGiVPmFPH/IToLWSxO99EFFCGuRUAnVBOpYPiRxRFIA4OZYsPcPSSFyxUS0zDxlr8d5B/chQV63GvG8/C8SYfnb9W8FHJslqQsNf4cu1wbKnZlSQpQupdjagEDGZnNuYVlQa4Ml9ouL+OG+5C3XSkbKcfke6qJ6y2+dOiPchLC+HDVld8JRoOcnn9qoh6NMCDeHQg3utaeLdz3T7/OjphGrjbMeqSq+3VU7m0GPoml38hYMqCmLJQG3aw2nOS1/QypyGFdd68w5477PN3uZCMGSe5v0nwRlKkZjeRhL/YcY50K6jEVDgSh1WFZybw5asDkBFlEp2ogH+qLgba1qpAGIfmsXqyXHaKynmPFl43nSLqR4e3DPbom+zzULRbDdQ7wkNdLqEriptJWq2UQWEEFlqpdZijKZz+C06w="
  on:
    branch: master
notifications:
  email: false