sudo: false
language: python

dist: bionic
os:
- linux

services:
  - docker
  - mysql

python:
- 3.7

jobs:
  include:
  - name: Unit tests
    install:
    - pip install .
    script: ./tests/run_tests.sh
    after_success:
    - coveralls
  - name: SciDAP workflow tests
    before_install:
    - mysql -e "CREATE DATABASE airflow;"
    - mysql -e "CREATE USER 'airflow'@'localhost' IDENTIFIED BY 'airflow';"
    - mysql -e "CREATE USER 'airflow'@'%' IDENTIFIED BY 'airflow';"
    - mysql -e "GRANT ALL PRIVILEGES ON airflow.* TO 'airflow'@'localhost';"
    - mysql -e "GRANT ALL PRIVILEGES ON airflow.* TO 'airflow'@'%';'"
    - git clone https://github.com/datirium/workflows.git --recursive
    install:
    - pip install .
    - pip install mysqlclient
    before_script:
    - airflow --help          # to generate airflow.cfg
    - cat ~travis/.my.cnf     # to see what it the socket for mysql
    - sed -i'.backup' -e 's/^executor.*/executor = LocalExecutor/g' ~/airflow/airflow.cfg
    - sed -i'.backup' -e 's/^dag_dir_list_interval =.*/dag_dir_list_interval = 60/g' ~/airflow/airflow.cfg
    - sed -i'.backup' -e 's/^parallelism =.*/parallelism = 1/g' ~/airflow/airflow.cfg
    - sed -i'.backup' -e 's/^sql_alchemy_conn.*/sql_alchemy_conn = mysql:\/\/airflow:airflow@127.0.0.1:3306\/airflow/g' ~/airflow/airflow.cfg
    - cat ~/airflow/airflow.cfg  # to check if airflow.cfg was updated
    - airflow initdb             # remove it later. just to see the error
    - cwl-airflow init           # to init database and add process_report connection
    - airflow connections -l     # to check if connection was added
    - airflow checkdb            # to check if we can connect to database
    - airflow scheduler > /dev/null 2>&1 &
    - cwl-airflow api > /dev/null 2>&1 &
    script: cwl-airflow test --suite workflows/tests/conformance_tests.yaml --spin --range 1

branches:
  only:
  - global_refactoring

notifications:
  email: false
