sudo: false
language: python

dist: bionic
os:
- linux

python:
- 3.7

install:
- pip install .

script: ./tests/run_tests.sh

after_success:
- coveralls

branches:
  only:
  - global_refactoring

notifications:
  email: false
