# -*- mode: ruby -*-
# vi: set ft=ruby :

$init_database = <<-EOS
  echo Running database init
  systemctl start mysql.service
EOS

$configure_airflow = <<-EOS
  echo Configuring Airflow
  sed -i 's/^executor.*/executor = LocalExecutor/g' /home/vagrant/airflow/airflow.cfg
  sed -i 's/^logging_level.*/logging_level = WARNING/g' /home/vagrant/airflow/airflow.cfg
  sed -i 's/.*sql_alchemy_conn.*/sql_alchemy_conn = mysql:\\/\\/airflow:airflow@127.0.0.1:3306\\/airflow/g' /home/vagrant/airflow/airflow.cfg
  cwl-airflow init
EOS

$init_master = <<-EOS
  echo Running master init
  systemctl start airflow-scheduler.service
  systemctl start airflow-webserver.service
EOS

def mount_folders(machine)
  machine.vm.synced_folder "airflow/temp",    "/tmp/cwlairflow",               create: true
  machine.vm.synced_folder "airflow/dags",    "/home/vagrant/airflow/dags",    create: true
  machine.vm.synced_folder "airflow/jobs",    "/home/vagrant/airflow/jobs",    create: true
  machine.vm.synced_folder "airflow/demo",    "/home/vagrant/airflow/demo",    create: true
  machine.vm.synced_folder "airflow/results", "/home/vagrant/airflow/results", create: true
end

Vagrant.configure("2") do |machine|
  machine.vm.box = "michael_kotliar/cwl-airflow"
  machine.vm.box_version = "0.0.4"
  machine.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  machine.vm.network "forwarded_port", guest: 3306, host: 6603, host_ip: "127.0.0.1"
  machine.vm.define "master"
  machine.vm.hostname = "master"
  mount_folders(machine)
  machine.vm.provision "shell", inline: $init_database,     privileged: true,  run: 'always'
  machine.vm.provision "shell", inline: $configure_airflow, privileged: false, run: 'always'
  machine.vm.provision "shell", inline: $init_master,       privileged: true,  run: 'always'
  machine.vm.provider "virtualbox" do |vbox|
    vbox.memory = 4096
    vbox.cpus = 4
    vbox.name = "master"
  end
end
