#!/bin/bash
BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
export PYTHONPATH="$BASE_DIR/lib/python3.*/site-packages"
export PATH="$BASE_DIR/bin":"$PATH":"/usr/local/bin:/usr/bin:/bin"
python3 cwl-airflow "$@"