#!/bin/bash
CONTENTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
export PYTHONPATH="$CONTENTS_DIR/Resources/app":"$CONTENTS_DIR/Resources/app_packages"
cd "$CONTENTS_DIR/Resources"
python/bin/python3 ./app/bin/cwl-airflow init
python/bin/python3 -m cwl_airflow
